services:
  - type: web
    name: pdflibre-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
